services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cosmetic_seo
      POSTGRES_USER: seo_user
      POSTGRES_PASSWORD: seo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seo_user -d cosmetic_seo"]
      interval: 5s
      timeout: 3s
      retries: 5

  cosmetic-seo-extractor:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Google Cloud & Gemini API
      GOOGLE_CLOUD_PROJECT: meeting-agent-463411
      GOOGLE_CLOUD_LOCATION: us-central1
      GOOGLE_GENAI_USE_VERTEXAI: "false"
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
      GOOGLE_API_KEY: AIzaSyDp4RpfCVU28H4j5d6n-6bzo1n8vqp3hqw
      
      # Database
      DATABASE_URL: postgresql://seo_user:seo_password@postgres:5432/cosmetic_seo
      
      # Application settings
      LOG_LEVEL: INFO
      MAX_PRODUCTS: 100
      RATE_LIMIT_SECONDS: 3
      TEST_MODE: "false"
      
      # Email settings (if needed)
      SENDER_EMAIL: vverlumea@gmail.com
      SENDER_PASSWORD: fpqfowuxgfxfuswf
      SENDER_NAME: "Cosmetic SEO Extractor"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./credentials.json:/app/credentials.json:ro
    restart: unless-stopped
    command: python main.py

  # Web UI - Kullanıcı Arayüzü
  web-ui:
    build: .
    depends_on:
      - postgres
    environment:
      GOOGLE_CLOUD_PROJECT: meeting-agent-463411
      GOOGLE_CLOUD_LOCATION: us-central1
      GOOGLE_GENAI_USE_VERTEXAI: "false"
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
      GOOGLE_API_KEY: AIzaSyDp4RpfCVU28H4j5d6n-6bzo1n8vqp3hqw
      DATABASE_URL: postgresql://seo_user:seo_password@postgres:5432/cosmetic_seo
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./credentials.json:/app/credentials.json:ro
    command: uvicorn web_app:app --host 0.0.0.0 --port 3000
    restart: unless-stopped

  # ADK Development UI (optional)
  adk-ui:
    build: .
    depends_on:
      - postgres
    environment:
      GOOGLE_CLOUD_PROJECT: meeting-agent-463411
      GOOGLE_CLOUD_LOCATION: us-central1
      GOOGLE_GENAI_USE_VERTEXAI: "false"
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
      GOOGLE_API_KEY: AIzaSyDp4RpfCVU28H4j5d6n-6bzo1n8vqp3hqw
      DATABASE_URL: postgresql://seo_user:seo_password@postgres:5432/cosmetic_seo
    ports:
      - "8000:8000"
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    command: adk web --host 0.0.0.0 --port 8000
    restart: unless-stopped

volumes:
  postgres_data: