version: '3.8'

services:
  simple-test:
    build:
      context: .
      dockerfile: Dockerfile.simple
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
    restart: "no"